version: '3.8'
services:
  db:
    image: postgres:17
    container_name: free-images-pg-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-freeimages}
    ports:
      - '5432:5432'
    volumes:
      - freeimages-pg-data:/var/lib/postgresql/data

volumes:
  freeimages-pg-data: